### ISSUE TITLE
Error: Invalid json format

### ISSUE THREAD

**Issue by nireno** [eldh/bs-reach#2]
I started a fresh react-hooks project and added bs-reach but I'm getting `Error: Invalid json format` when trying to run bsb after adding bs-reach to my bsconfig dependencies.

I looked into the bs-reach folder in node_modules and it seems to be missing a bsconfig file.

I can get things to build by manually adding a bsconfig file at node_modules/bs-reach/bsconfig.json

bs-reach version "0.2.0"

**Comment by eldh** [comment]
Thanks. Should be fixed now. Try installing 0.2.1 as see if that works.

**Comment by nireno** [comment]
Hey, thanks.
Now I'm getting something like: `Error: node_modules/bs-reach/examples: No such file or directory`
I'm guessing its because `npm install`ed version doesn't keep the examples directory but the bsconfig file is still pointing to it.

**Comment by eldh** [comment]
Damn I was afraid of that. Didn't get the warning when I tried but I had other problems in my test repo. Merged your PR and released 0.2.2.

**Comment by eldh** [comment]
0.3.0 Also removes the bs-css dependency which was a bit of an issue. Closing.
