### ISSUE TITLE
Installed and added to bsconfig but not showing up.

### ISSUE THREAD

**Issue by vasco3** [eldh/bs-reach#4]
I followed the instructions on the README. But seems like it isn't working. RLS is not recognizing the reach ui components.

Any idea on how to fix this?

**Comment by eldh** [comment]
Could you provide a repo which demonstrates the issue? Just tried myself and it works. (the namespace is `Reach`).

I'll close the issue for now and re-open if needed.

**Comment by vasco3** [comment]
that was it! thanks

**Comment by eldh** [comment]
I'll add that to the readme :)
