### ISSUE TITLE
Tooltip module is not found

### ISSUE THREAD

**Issue by vasco3** [eldh/bs-reach#6]
I'm getting this error 
`Module not found: Can't resolve 'reach/src/Tooltip.bs.js' `

Trying to use it 
```reasonml
open Reach

[@react.component]
let make =()=>{
    <Tooltip label="text"><img src="/logo.png"/></Tooltip>
};
```
does it work for you?

**Comment by eldh** [comment]
Thanks, it was indeed an issue. Should be fixed in latest release, 0.5.2.
