### ISSUE TITLE
move reason-react to dev/peer dependency?

### ISSUE THREAD

**Issue by logandeancall** [eldh/bs-reach#7]
Should reason-react be moved to a dev dependency so that the consumer of this library can control what version of reason-react they are using without having duplicate copies?

**Comment by eldh** [comment]
Yeah, makes sense. Want to make a PR? Otherwise I'll try to fix in the coming days.

**Comment by logandeancall** [comment]
Happy to. Would you want it in just the dev dependencies or both dev and peer dependencies?

**Comment by eldh** [comment]
Just dev is enough I think. No one cares about peer dependencies warnings anyway. If it breaks it will break on compilation.
